---
- name: Add elastic's public signing key
  apt_key:
    url: 'https://packages.elasticsearch.org/GPG-KEY-elasticsearch'
    state: present
  tags:
    - apt

- name: Add logstash repository
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/logstash/{{ logstash_version_major_minor }}/debian stable main"
    state: present
    update_cache: yes
  tags:
    - apt

- name: Install logstash and patch
  apt:
    package: "{{ item }}"
    state: present
  with_items:
    - logstash
    - patch
  tags:
    - apt

- name: Add logstash user to adm group
  user:
    name: logstash
    group: logstash
    groups: adm
  when: logstash_input_syslog.enable
  notify: restart logstash
